package com.yc.demo.domain;

import com.yc.demo.domain.ex.BasePoJo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_assembly_content
 *
 * @mbg.generated do_not_delete_during_merge Fri Apr 09 23:56:57 CST 2021
 */
public class TbAssemblyContent extends BasePoJo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.id
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   对应config表的type=qualityInspectionModel的Key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.config_key
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private String configKey;

    /**
     * Database Column Remarks:
     *   装配名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.content_name
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private String contentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.remark
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.create_time
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.update_time
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   1可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.enable
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private Integer enable;

    /**
     * Database Column Remarks:
     *   0抽样1基础
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.sampling_flag
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private Integer samplingFlag;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.position
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.create_user
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_assembly_content.update_user
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.id
     *
     * @return the value of tb_assembly_content.id
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.id
     *
     * @param id the value for tb_assembly_content.id
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.config_key
     *
     * @return the value of tb_assembly_content.config_key
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.config_key
     *
     * @param configKey the value for tb_assembly_content.config_key
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.content_name
     *
     * @return the value of tb_assembly_content.content_name
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public String getContentName() {
        return contentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.content_name
     *
     * @param contentName the value for tb_assembly_content.content_name
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setContentName(String contentName) {
        this.contentName = contentName == null ? null : contentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.remark
     *
     * @return the value of tb_assembly_content.remark
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.remark
     *
     * @param remark the value for tb_assembly_content.remark
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.create_time
     *
     * @return the value of tb_assembly_content.create_time
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.create_time
     *
     * @param createTime the value for tb_assembly_content.create_time
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.update_time
     *
     * @return the value of tb_assembly_content.update_time
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.update_time
     *
     * @param updateTime the value for tb_assembly_content.update_time
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.enable
     *
     * @return the value of tb_assembly_content.enable
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.enable
     *
     * @param enable the value for tb_assembly_content.enable
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.sampling_flag
     *
     * @return the value of tb_assembly_content.sampling_flag
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public Integer getSamplingFlag() {
        return samplingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.sampling_flag
     *
     * @param samplingFlag the value for tb_assembly_content.sampling_flag
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setSamplingFlag(Integer samplingFlag) {
        this.samplingFlag = samplingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.position
     *
     * @return the value of tb_assembly_content.position
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.position
     *
     * @param position the value for tb_assembly_content.position
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.create_user
     *
     * @return the value of tb_assembly_content.create_user
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.create_user
     *
     * @param createUser the value for tb_assembly_content.create_user
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_assembly_content.update_user
     *
     * @return the value of tb_assembly_content.update_user
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_assembly_content.update_user
     *
     * @param updateUser the value for tb_assembly_content.update_user
     *
     * @mbg.generated Fri Apr 09 23:56:57 CST 2021
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}