package com.yc.demo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbOrderWarehouseLocationTransferExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public TbOrderWarehouseLocationTransferExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionIsNull() {
            addCriterion("original_position is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionIsNotNull() {
            addCriterion("original_position is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionEqualTo(String value) {
            addCriterion("original_position =", value, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionNotEqualTo(String value) {
            addCriterion("original_position <>", value, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionGreaterThan(String value) {
            addCriterion("original_position >", value, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionGreaterThanOrEqualTo(String value) {
            addCriterion("original_position >=", value, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionLessThan(String value) {
            addCriterion("original_position <", value, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionLessThanOrEqualTo(String value) {
            addCriterion("original_position <=", value, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionLike(String value) {
            addCriterion("original_position like", value, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionNotLike(String value) {
            addCriterion("original_position not like", value, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionIn(List<String> values) {
            addCriterion("original_position in", values, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionNotIn(List<String> values) {
            addCriterion("original_position not in", values, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionBetween(String value1, String value2) {
            addCriterion("original_position between", value1, value2, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andOriginalPositionNotBetween(String value1, String value2) {
            addCriterion("original_position not between", value1, value2, "originalPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionIsNull() {
            addCriterion("new_position is null");
            return (Criteria) this;
        }

        public Criteria andNewPositionIsNotNull() {
            addCriterion("new_position is not null");
            return (Criteria) this;
        }

        public Criteria andNewPositionEqualTo(String value) {
            addCriterion("new_position =", value, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionNotEqualTo(String value) {
            addCriterion("new_position <>", value, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionGreaterThan(String value) {
            addCriterion("new_position >", value, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionGreaterThanOrEqualTo(String value) {
            addCriterion("new_position >=", value, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionLessThan(String value) {
            addCriterion("new_position <", value, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionLessThanOrEqualTo(String value) {
            addCriterion("new_position <=", value, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionLike(String value) {
            addCriterion("new_position like", value, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionNotLike(String value) {
            addCriterion("new_position not like", value, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionIn(List<String> values) {
            addCriterion("new_position in", values, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionNotIn(List<String> values) {
            addCriterion("new_position not in", values, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionBetween(String value1, String value2) {
            addCriterion("new_position between", value1, value2, "newPosition");
            return (Criteria) this;
        }

        public Criteria andNewPositionNotBetween(String value1, String value2) {
            addCriterion("new_position not between", value1, value2, "newPosition");
            return (Criteria) this;
        }

        public Criteria andItemNumIsNull() {
            addCriterion("item_num is null");
            return (Criteria) this;
        }

        public Criteria andItemNumIsNotNull() {
            addCriterion("item_num is not null");
            return (Criteria) this;
        }

        public Criteria andItemNumEqualTo(String value) {
            addCriterion("item_num =", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotEqualTo(String value) {
            addCriterion("item_num <>", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumGreaterThan(String value) {
            addCriterion("item_num >", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumGreaterThanOrEqualTo(String value) {
            addCriterion("item_num >=", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumLessThan(String value) {
            addCriterion("item_num <", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumLessThanOrEqualTo(String value) {
            addCriterion("item_num <=", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumLike(String value) {
            addCriterion("item_num like", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotLike(String value) {
            addCriterion("item_num not like", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumIn(List<String> values) {
            addCriterion("item_num in", values, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotIn(List<String> values) {
            addCriterion("item_num not in", values, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumBetween(String value1, String value2) {
            addCriterion("item_num between", value1, value2, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotBetween(String value1, String value2) {
            addCriterion("item_num not between", value1, value2, "itemNum");
            return (Criteria) this;
        }

        public Criteria andComeTimeIsNull() {
            addCriterion("come_time is null");
            return (Criteria) this;
        }

        public Criteria andComeTimeIsNotNull() {
            addCriterion("come_time is not null");
            return (Criteria) this;
        }

        public Criteria andComeTimeEqualTo(Date value) {
            addCriterion("come_time =", value, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeNotEqualTo(Date value) {
            addCriterion("come_time <>", value, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeGreaterThan(Date value) {
            addCriterion("come_time >", value, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("come_time >=", value, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeLessThan(Date value) {
            addCriterion("come_time <", value, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeLessThanOrEqualTo(Date value) {
            addCriterion("come_time <=", value, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeIn(List<Date> values) {
            addCriterion("come_time in", values, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeNotIn(List<Date> values) {
            addCriterion("come_time not in", values, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeBetween(Date value1, Date value2) {
            addCriterion("come_time between", value1, value2, "comeTime");
            return (Criteria) this;
        }

        public Criteria andComeTimeNotBetween(Date value1, Date value2) {
            addCriterion("come_time not between", value1, value2, "comeTime");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Integer value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Integer value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Integer value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Integer value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Integer> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Integer> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Integer value1, Integer value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseIsNull() {
            addCriterion("original_warehouse is null");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseIsNotNull() {
            addCriterion("original_warehouse is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseEqualTo(String value) {
            addCriterion("original_warehouse =", value, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseNotEqualTo(String value) {
            addCriterion("original_warehouse <>", value, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseGreaterThan(String value) {
            addCriterion("original_warehouse >", value, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseGreaterThanOrEqualTo(String value) {
            addCriterion("original_warehouse >=", value, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseLessThan(String value) {
            addCriterion("original_warehouse <", value, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseLessThanOrEqualTo(String value) {
            addCriterion("original_warehouse <=", value, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseLike(String value) {
            addCriterion("original_warehouse like", value, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseNotLike(String value) {
            addCriterion("original_warehouse not like", value, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseIn(List<String> values) {
            addCriterion("original_warehouse in", values, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseNotIn(List<String> values) {
            addCriterion("original_warehouse not in", values, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseBetween(String value1, String value2) {
            addCriterion("original_warehouse between", value1, value2, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalWarehouseNotBetween(String value1, String value2) {
            addCriterion("original_warehouse not between", value1, value2, "originalWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseIsNull() {
            addCriterion("new_warehouse is null");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseIsNotNull() {
            addCriterion("new_warehouse is not null");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseEqualTo(String value) {
            addCriterion("new_warehouse =", value, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseNotEqualTo(String value) {
            addCriterion("new_warehouse <>", value, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseGreaterThan(String value) {
            addCriterion("new_warehouse >", value, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseGreaterThanOrEqualTo(String value) {
            addCriterion("new_warehouse >=", value, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseLessThan(String value) {
            addCriterion("new_warehouse <", value, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseLessThanOrEqualTo(String value) {
            addCriterion("new_warehouse <=", value, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseLike(String value) {
            addCriterion("new_warehouse like", value, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseNotLike(String value) {
            addCriterion("new_warehouse not like", value, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseIn(List<String> values) {
            addCriterion("new_warehouse in", values, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseNotIn(List<String> values) {
            addCriterion("new_warehouse not in", values, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseBetween(String value1, String value2) {
            addCriterion("new_warehouse between", value1, value2, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andNewWarehouseNotBetween(String value1, String value2) {
            addCriterion("new_warehouse not between", value1, value2, "newWarehouse");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationIsNull() {
            addCriterion("original_location is null");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationIsNotNull() {
            addCriterion("original_location is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationEqualTo(String value) {
            addCriterion("original_location =", value, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationNotEqualTo(String value) {
            addCriterion("original_location <>", value, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationGreaterThan(String value) {
            addCriterion("original_location >", value, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationGreaterThanOrEqualTo(String value) {
            addCriterion("original_location >=", value, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationLessThan(String value) {
            addCriterion("original_location <", value, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationLessThanOrEqualTo(String value) {
            addCriterion("original_location <=", value, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationLike(String value) {
            addCriterion("original_location like", value, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationNotLike(String value) {
            addCriterion("original_location not like", value, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationIn(List<String> values) {
            addCriterion("original_location in", values, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationNotIn(List<String> values) {
            addCriterion("original_location not in", values, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationBetween(String value1, String value2) {
            addCriterion("original_location between", value1, value2, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andOriginalLocationNotBetween(String value1, String value2) {
            addCriterion("original_location not between", value1, value2, "originalLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationIsNull() {
            addCriterion("new_location is null");
            return (Criteria) this;
        }

        public Criteria andNewLocationIsNotNull() {
            addCriterion("new_location is not null");
            return (Criteria) this;
        }

        public Criteria andNewLocationEqualTo(String value) {
            addCriterion("new_location =", value, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationNotEqualTo(String value) {
            addCriterion("new_location <>", value, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationGreaterThan(String value) {
            addCriterion("new_location >", value, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationGreaterThanOrEqualTo(String value) {
            addCriterion("new_location >=", value, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationLessThan(String value) {
            addCriterion("new_location <", value, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationLessThanOrEqualTo(String value) {
            addCriterion("new_location <=", value, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationLike(String value) {
            addCriterion("new_location like", value, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationNotLike(String value) {
            addCriterion("new_location not like", value, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationIn(List<String> values) {
            addCriterion("new_location in", values, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationNotIn(List<String> values) {
            addCriterion("new_location not in", values, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationBetween(String value1, String value2) {
            addCriterion("new_location between", value1, value2, "newLocation");
            return (Criteria) this;
        }

        public Criteria andNewLocationNotBetween(String value1, String value2) {
            addCriterion("new_location not between", value1, value2, "newLocation");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Long value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Long value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Long value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Long value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Long value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Long> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Long> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Long value1, Long value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Long value1, Long value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Long value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Long value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Long value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Long value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Long value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Long value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Long> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Long> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Long value1, Long value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Long value1, Long value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Integer value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Integer value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Integer value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Integer value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Integer value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Integer> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Integer> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Integer value1, Integer value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated do_not_delete_during_merge Sat May 29 19:26:28 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}