package com.yc.demo.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_order_shortage
 *
 * @mbg.generated do_not_delete_during_merge Sat May 29 19:26:21 CST 2021
 */
public class TbOrderShortage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.id
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   工单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.order_no
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private String orderNo;

    /**
     * Database Column Remarks:
     *   物料号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.item_no
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private String itemNo;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   预计到货日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.estimate_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Date estimateTime;

    /**
     * Database Column Remarks:
     *   预计到货数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.estimate_quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Integer estimateQuantity;

    /**
     * Database Column Remarks:
     *   实际到货日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.actual_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Date actualTime;

    /**
     * Database Column Remarks:
     *   实际到货数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.actual_quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Integer actualQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.remark
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.create_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.update_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.create_user
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.update_user
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Long updateUser;

    /**
     * Database Column Remarks:
     *   1可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_shortage.enable
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.id
     *
     * @return the value of tb_order_shortage.id
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.id
     *
     * @param id the value for tb_order_shortage.id
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.order_no
     *
     * @return the value of tb_order_shortage.order_no
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.order_no
     *
     * @param orderNo the value for tb_order_shortage.order_no
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.item_no
     *
     * @return the value of tb_order_shortage.item_no
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.item_no
     *
     * @param itemNo the value for tb_order_shortage.item_no
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.quantity
     *
     * @return the value of tb_order_shortage.quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.quantity
     *
     * @param quantity the value for tb_order_shortage.quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.estimate_time
     *
     * @return the value of tb_order_shortage.estimate_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Date getEstimateTime() {
        return estimateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.estimate_time
     *
     * @param estimateTime the value for tb_order_shortage.estimate_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setEstimateTime(Date estimateTime) {
        this.estimateTime = estimateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.estimate_quantity
     *
     * @return the value of tb_order_shortage.estimate_quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Integer getEstimateQuantity() {
        return estimateQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.estimate_quantity
     *
     * @param estimateQuantity the value for tb_order_shortage.estimate_quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setEstimateQuantity(Integer estimateQuantity) {
        this.estimateQuantity = estimateQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.actual_time
     *
     * @return the value of tb_order_shortage.actual_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Date getActualTime() {
        return actualTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.actual_time
     *
     * @param actualTime the value for tb_order_shortage.actual_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setActualTime(Date actualTime) {
        this.actualTime = actualTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.actual_quantity
     *
     * @return the value of tb_order_shortage.actual_quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Integer getActualQuantity() {
        return actualQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.actual_quantity
     *
     * @param actualQuantity the value for tb_order_shortage.actual_quantity
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setActualQuantity(Integer actualQuantity) {
        this.actualQuantity = actualQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.remark
     *
     * @return the value of tb_order_shortage.remark
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.remark
     *
     * @param remark the value for tb_order_shortage.remark
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.create_time
     *
     * @return the value of tb_order_shortage.create_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.create_time
     *
     * @param createTime the value for tb_order_shortage.create_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.update_time
     *
     * @return the value of tb_order_shortage.update_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.update_time
     *
     * @param updateTime the value for tb_order_shortage.update_time
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.create_user
     *
     * @return the value of tb_order_shortage.create_user
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.create_user
     *
     * @param createUser the value for tb_order_shortage.create_user
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.update_user
     *
     * @return the value of tb_order_shortage.update_user
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.update_user
     *
     * @param updateUser the value for tb_order_shortage.update_user
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_shortage.enable
     *
     * @return the value of tb_order_shortage.enable
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_shortage.enable
     *
     * @param enable the value for tb_order_shortage.enable
     *
     * @mbg.generated Sat May 29 19:26:21 CST 2021
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}