package com.yc.demo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbOrderGeneralExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public TbOrderGeneralExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDefTypeIsNull() {
            addCriterion("def_type is null");
            return (Criteria) this;
        }

        public Criteria andDefTypeIsNotNull() {
            addCriterion("def_type is not null");
            return (Criteria) this;
        }

        public Criteria andDefTypeEqualTo(Integer value) {
            addCriterion("def_type =", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeNotEqualTo(Integer value) {
            addCriterion("def_type <>", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeGreaterThan(Integer value) {
            addCriterion("def_type >", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("def_type >=", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeLessThan(Integer value) {
            addCriterion("def_type <", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeLessThanOrEqualTo(Integer value) {
            addCriterion("def_type <=", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeIn(List<Integer> values) {
            addCriterion("def_type in", values, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeNotIn(List<Integer> values) {
            addCriterion("def_type not in", values, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeBetween(Integer value1, Integer value2) {
            addCriterion("def_type between", value1, value2, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("def_type not between", value1, value2, "defType");
            return (Criteria) this;
        }

        public Criteria andGroupUuidIsNull() {
            addCriterion("group_uuid is null");
            return (Criteria) this;
        }

        public Criteria andGroupUuidIsNotNull() {
            addCriterion("group_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andGroupUuidEqualTo(String value) {
            addCriterion("group_uuid =", value, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidNotEqualTo(String value) {
            addCriterion("group_uuid <>", value, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidGreaterThan(String value) {
            addCriterion("group_uuid >", value, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidGreaterThanOrEqualTo(String value) {
            addCriterion("group_uuid >=", value, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidLessThan(String value) {
            addCriterion("group_uuid <", value, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidLessThanOrEqualTo(String value) {
            addCriterion("group_uuid <=", value, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidLike(String value) {
            addCriterion("group_uuid like", value, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidNotLike(String value) {
            addCriterion("group_uuid not like", value, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidIn(List<String> values) {
            addCriterion("group_uuid in", values, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidNotIn(List<String> values) {
            addCriterion("group_uuid not in", values, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidBetween(String value1, String value2) {
            addCriterion("group_uuid between", value1, value2, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andGroupUuidNotBetween(String value1, String value2) {
            addCriterion("group_uuid not between", value1, value2, "groupUuid");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeIsNull() {
            addCriterion("before_acl_code is null");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeIsNotNull() {
            addCriterion("before_acl_code is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeEqualTo(String value) {
            addCriterion("before_acl_code =", value, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeNotEqualTo(String value) {
            addCriterion("before_acl_code <>", value, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeGreaterThan(String value) {
            addCriterion("before_acl_code >", value, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeGreaterThanOrEqualTo(String value) {
            addCriterion("before_acl_code >=", value, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeLessThan(String value) {
            addCriterion("before_acl_code <", value, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeLessThanOrEqualTo(String value) {
            addCriterion("before_acl_code <=", value, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeLike(String value) {
            addCriterion("before_acl_code like", value, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeNotLike(String value) {
            addCriterion("before_acl_code not like", value, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeIn(List<String> values) {
            addCriterion("before_acl_code in", values, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeNotIn(List<String> values) {
            addCriterion("before_acl_code not in", values, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeBetween(String value1, String value2) {
            addCriterion("before_acl_code between", value1, value2, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeAclCodeNotBetween(String value1, String value2) {
            addCriterion("before_acl_code not between", value1, value2, "beforeAclCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeIsNull() {
            addCriterion("before_user_code is null");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeIsNotNull() {
            addCriterion("before_user_code is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeEqualTo(String value) {
            addCriterion("before_user_code =", value, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeNotEqualTo(String value) {
            addCriterion("before_user_code <>", value, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeGreaterThan(String value) {
            addCriterion("before_user_code >", value, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("before_user_code >=", value, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeLessThan(String value) {
            addCriterion("before_user_code <", value, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeLessThanOrEqualTo(String value) {
            addCriterion("before_user_code <=", value, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeLike(String value) {
            addCriterion("before_user_code like", value, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeNotLike(String value) {
            addCriterion("before_user_code not like", value, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeIn(List<String> values) {
            addCriterion("before_user_code in", values, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeNotIn(List<String> values) {
            addCriterion("before_user_code not in", values, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeBetween(String value1, String value2) {
            addCriterion("before_user_code between", value1, value2, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andBeforeUserCodeNotBetween(String value1, String value2) {
            addCriterion("before_user_code not between", value1, value2, "beforeUserCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeIsNull() {
            addCriterion("now_acl_code is null");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeIsNotNull() {
            addCriterion("now_acl_code is not null");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeEqualTo(String value) {
            addCriterion("now_acl_code =", value, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeNotEqualTo(String value) {
            addCriterion("now_acl_code <>", value, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeGreaterThan(String value) {
            addCriterion("now_acl_code >", value, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeGreaterThanOrEqualTo(String value) {
            addCriterion("now_acl_code >=", value, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeLessThan(String value) {
            addCriterion("now_acl_code <", value, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeLessThanOrEqualTo(String value) {
            addCriterion("now_acl_code <=", value, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeLike(String value) {
            addCriterion("now_acl_code like", value, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeNotLike(String value) {
            addCriterion("now_acl_code not like", value, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeIn(List<String> values) {
            addCriterion("now_acl_code in", values, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeNotIn(List<String> values) {
            addCriterion("now_acl_code not in", values, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeBetween(String value1, String value2) {
            addCriterion("now_acl_code between", value1, value2, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowAclCodeNotBetween(String value1, String value2) {
            addCriterion("now_acl_code not between", value1, value2, "nowAclCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeIsNull() {
            addCriterion("now_user_code is null");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeIsNotNull() {
            addCriterion("now_user_code is not null");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeEqualTo(String value) {
            addCriterion("now_user_code =", value, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeNotEqualTo(String value) {
            addCriterion("now_user_code <>", value, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeGreaterThan(String value) {
            addCriterion("now_user_code >", value, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("now_user_code >=", value, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeLessThan(String value) {
            addCriterion("now_user_code <", value, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeLessThanOrEqualTo(String value) {
            addCriterion("now_user_code <=", value, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeLike(String value) {
            addCriterion("now_user_code like", value, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeNotLike(String value) {
            addCriterion("now_user_code not like", value, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeIn(List<String> values) {
            addCriterion("now_user_code in", values, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeNotIn(List<String> values) {
            addCriterion("now_user_code not in", values, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeBetween(String value1, String value2) {
            addCriterion("now_user_code between", value1, value2, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNowUserCodeNotBetween(String value1, String value2) {
            addCriterion("now_user_code not between", value1, value2, "nowUserCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeIsNull() {
            addCriterion("next_acl_code is null");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeIsNotNull() {
            addCriterion("next_acl_code is not null");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeEqualTo(String value) {
            addCriterion("next_acl_code =", value, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeNotEqualTo(String value) {
            addCriterion("next_acl_code <>", value, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeGreaterThan(String value) {
            addCriterion("next_acl_code >", value, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeGreaterThanOrEqualTo(String value) {
            addCriterion("next_acl_code >=", value, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeLessThan(String value) {
            addCriterion("next_acl_code <", value, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeLessThanOrEqualTo(String value) {
            addCriterion("next_acl_code <=", value, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeLike(String value) {
            addCriterion("next_acl_code like", value, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeNotLike(String value) {
            addCriterion("next_acl_code not like", value, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeIn(List<String> values) {
            addCriterion("next_acl_code in", values, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeNotIn(List<String> values) {
            addCriterion("next_acl_code not in", values, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeBetween(String value1, String value2) {
            addCriterion("next_acl_code between", value1, value2, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextAclCodeNotBetween(String value1, String value2) {
            addCriterion("next_acl_code not between", value1, value2, "nextAclCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeIsNull() {
            addCriterion("next_user_code is null");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeIsNotNull() {
            addCriterion("next_user_code is not null");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeEqualTo(String value) {
            addCriterion("next_user_code =", value, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeNotEqualTo(String value) {
            addCriterion("next_user_code <>", value, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeGreaterThan(String value) {
            addCriterion("next_user_code >", value, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("next_user_code >=", value, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeLessThan(String value) {
            addCriterion("next_user_code <", value, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeLessThanOrEqualTo(String value) {
            addCriterion("next_user_code <=", value, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeLike(String value) {
            addCriterion("next_user_code like", value, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeNotLike(String value) {
            addCriterion("next_user_code not like", value, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeIn(List<String> values) {
            addCriterion("next_user_code in", values, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeNotIn(List<String> values) {
            addCriterion("next_user_code not in", values, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeBetween(String value1, String value2) {
            addCriterion("next_user_code between", value1, value2, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andNextUserCodeNotBetween(String value1, String value2) {
            addCriterion("next_user_code not between", value1, value2, "nextUserCode");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Long value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Long value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Long value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Long value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Long value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Long> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Long> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Long value1, Long value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Long value1, Long value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Long value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Long value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Long value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Long value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Long value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Long value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Long> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Long> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Long value1, Long value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Long value1, Long value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Integer value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Integer value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Integer value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Integer value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Integer value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Integer> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Integer> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Integer value1, Integer value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_general
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 04 21:11:31 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_general
     *
     * @mbg.generated Fri Jun 04 21:11:31 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}