package com.yc.demo.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_order_production_supple
 *
 * @mbg.generated do_not_delete_during_merge Sat Jul 31 20:07:39 CST 2021
 */
public class TbOrderProductionSupple {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.id
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.group_uuid
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String groupUuid;

    /**
     * Database Column Remarks:
     *   工单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.order_no
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String orderNo;

    /**
     * Database Column Remarks:
     *   料号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.item_no
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String itemNo;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.quantity
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.name
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String name;

    /**
     * Database Column Remarks:
     *   原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.reason
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.standard_cost
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private BigDecimal standardCost;

    /**
     * Database Column Remarks:
     *   总成本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.total_cost
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private BigDecimal totalCost;

    /**
     * Database Column Remarks:
     *   说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.explain_remark
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String explainRemark;

    /**
     * Database Column Remarks:
     *   仓库
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.warehouse
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String warehouse;

    /**
     * Database Column Remarks:
     *   库位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.location
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.remark
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.create_time
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.update_time
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.create_user
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.update_user
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private Long updateUser;

    /**
     * Database Column Remarks:
     *   1可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.enable
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private Integer enable;

    /**
     * Database Column Remarks:
     *   产线名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_production_supple.production_line_name
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    private String productionLineName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.id
     *
     * @return the value of tb_order_production_supple.id
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.id
     *
     * @param id the value for tb_order_production_supple.id
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.group_uuid
     *
     * @return the value of tb_order_production_supple.group_uuid
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getGroupUuid() {
        return groupUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.group_uuid
     *
     * @param groupUuid the value for tb_order_production_supple.group_uuid
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setGroupUuid(String groupUuid) {
        this.groupUuid = groupUuid == null ? null : groupUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.order_no
     *
     * @return the value of tb_order_production_supple.order_no
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.order_no
     *
     * @param orderNo the value for tb_order_production_supple.order_no
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.item_no
     *
     * @return the value of tb_order_production_supple.item_no
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.item_no
     *
     * @param itemNo the value for tb_order_production_supple.item_no
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.quantity
     *
     * @return the value of tb_order_production_supple.quantity
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.quantity
     *
     * @param quantity the value for tb_order_production_supple.quantity
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.name
     *
     * @return the value of tb_order_production_supple.name
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.name
     *
     * @param name the value for tb_order_production_supple.name
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.reason
     *
     * @return the value of tb_order_production_supple.reason
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.reason
     *
     * @param reason the value for tb_order_production_supple.reason
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.standard_cost
     *
     * @return the value of tb_order_production_supple.standard_cost
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public BigDecimal getStandardCost() {
        return standardCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.standard_cost
     *
     * @param standardCost the value for tb_order_production_supple.standard_cost
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setStandardCost(BigDecimal standardCost) {
        this.standardCost = standardCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.total_cost
     *
     * @return the value of tb_order_production_supple.total_cost
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public BigDecimal getTotalCost() {
        return totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.total_cost
     *
     * @param totalCost the value for tb_order_production_supple.total_cost
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setTotalCost(BigDecimal totalCost) {
        this.totalCost = totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.explain_remark
     *
     * @return the value of tb_order_production_supple.explain_remark
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getExplainRemark() {
        return explainRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.explain_remark
     *
     * @param explainRemark the value for tb_order_production_supple.explain_remark
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setExplainRemark(String explainRemark) {
        this.explainRemark = explainRemark == null ? null : explainRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.warehouse
     *
     * @return the value of tb_order_production_supple.warehouse
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getWarehouse() {
        return warehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.warehouse
     *
     * @param warehouse the value for tb_order_production_supple.warehouse
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.location
     *
     * @return the value of tb_order_production_supple.location
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.location
     *
     * @param location the value for tb_order_production_supple.location
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.remark
     *
     * @return the value of tb_order_production_supple.remark
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.remark
     *
     * @param remark the value for tb_order_production_supple.remark
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.create_time
     *
     * @return the value of tb_order_production_supple.create_time
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.create_time
     *
     * @param createTime the value for tb_order_production_supple.create_time
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.update_time
     *
     * @return the value of tb_order_production_supple.update_time
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.update_time
     *
     * @param updateTime the value for tb_order_production_supple.update_time
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.create_user
     *
     * @return the value of tb_order_production_supple.create_user
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.create_user
     *
     * @param createUser the value for tb_order_production_supple.create_user
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.update_user
     *
     * @return the value of tb_order_production_supple.update_user
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.update_user
     *
     * @param updateUser the value for tb_order_production_supple.update_user
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.enable
     *
     * @return the value of tb_order_production_supple.enable
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.enable
     *
     * @param enable the value for tb_order_production_supple.enable
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_production_supple.production_line_name
     *
     * @return the value of tb_order_production_supple.production_line_name
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public String getProductionLineName() {
        return productionLineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_production_supple.production_line_name
     *
     * @param productionLineName the value for tb_order_production_supple.production_line_name
     *
     * @mbg.generated Sat Jul 31 20:07:39 CST 2021
     */
    public void setProductionLineName(String productionLineName) {
        this.productionLineName = productionLineName == null ? null : productionLineName.trim();
    }
}