package com.yc.demo.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_order_warehouse_location_transfer_ncm
 *
 * @mbg.generated do_not_delete_during_merge Thu Aug 12 19:12:56 CST 2021
 */
public class TbOrderWarehouseLocationTransferNcm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.id
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.group_uuid
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String groupUuid;

    /**
     * Database Column Remarks:
     *   ncm类型转入转出
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.ncm_type_name
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String ncmTypeName;

    /**
     * Database Column Remarks:
     *   原始位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.original_position
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String originalPosition;

    /**
     * Database Column Remarks:
     *   原因说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.reason
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String reason;

    /**
     * Database Column Remarks:
     *   新建位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.new_position
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String newPosition;

    /**
     * Database Column Remarks:
     *   物料号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.item_num
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String itemNum;

    /**
     * Database Column Remarks:
     *   来料日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.come_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private Date comeTime;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.quantity
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   老仓库
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.original_warehouse
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String originalWarehouse;

    /**
     * Database Column Remarks:
     *   新仓库
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.new_warehouse
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String newWarehouse;

    /**
     * Database Column Remarks:
     *   老库位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.original_location
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String originalLocation;

    /**
     * Database Column Remarks:
     *   新库位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.new_location
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String newLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.remark
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.create_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.update_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.create_user
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.update_user
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private Long updateUser;

    /**
     * Database Column Remarks:
     *   1可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_warehouse_location_transfer_ncm.enable
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.id
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.id
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.id
     *
     * @param id the value for tb_order_warehouse_location_transfer_ncm.id
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.group_uuid
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.group_uuid
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getGroupUuid() {
        return groupUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.group_uuid
     *
     * @param groupUuid the value for tb_order_warehouse_location_transfer_ncm.group_uuid
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setGroupUuid(String groupUuid) {
        this.groupUuid = groupUuid == null ? null : groupUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.ncm_type_name
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.ncm_type_name
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getNcmTypeName() {
        return ncmTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.ncm_type_name
     *
     * @param ncmTypeName the value for tb_order_warehouse_location_transfer_ncm.ncm_type_name
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setNcmTypeName(String ncmTypeName) {
        this.ncmTypeName = ncmTypeName == null ? null : ncmTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.original_position
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.original_position
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getOriginalPosition() {
        return originalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.original_position
     *
     * @param originalPosition the value for tb_order_warehouse_location_transfer_ncm.original_position
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setOriginalPosition(String originalPosition) {
        this.originalPosition = originalPosition == null ? null : originalPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.reason
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.reason
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.reason
     *
     * @param reason the value for tb_order_warehouse_location_transfer_ncm.reason
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.new_position
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.new_position
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getNewPosition() {
        return newPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.new_position
     *
     * @param newPosition the value for tb_order_warehouse_location_transfer_ncm.new_position
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setNewPosition(String newPosition) {
        this.newPosition = newPosition == null ? null : newPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.item_num
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.item_num
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.item_num
     *
     * @param itemNum the value for tb_order_warehouse_location_transfer_ncm.item_num
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setItemNum(String itemNum) {
        this.itemNum = itemNum == null ? null : itemNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.come_time
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.come_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public Date getComeTime() {
        return comeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.come_time
     *
     * @param comeTime the value for tb_order_warehouse_location_transfer_ncm.come_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setComeTime(Date comeTime) {
        this.comeTime = comeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.quantity
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.quantity
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.quantity
     *
     * @param quantity the value for tb_order_warehouse_location_transfer_ncm.quantity
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.original_warehouse
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.original_warehouse
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getOriginalWarehouse() {
        return originalWarehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.original_warehouse
     *
     * @param originalWarehouse the value for tb_order_warehouse_location_transfer_ncm.original_warehouse
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setOriginalWarehouse(String originalWarehouse) {
        this.originalWarehouse = originalWarehouse == null ? null : originalWarehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.new_warehouse
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.new_warehouse
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getNewWarehouse() {
        return newWarehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.new_warehouse
     *
     * @param newWarehouse the value for tb_order_warehouse_location_transfer_ncm.new_warehouse
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setNewWarehouse(String newWarehouse) {
        this.newWarehouse = newWarehouse == null ? null : newWarehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.original_location
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.original_location
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getOriginalLocation() {
        return originalLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.original_location
     *
     * @param originalLocation the value for tb_order_warehouse_location_transfer_ncm.original_location
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setOriginalLocation(String originalLocation) {
        this.originalLocation = originalLocation == null ? null : originalLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.new_location
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.new_location
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getNewLocation() {
        return newLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.new_location
     *
     * @param newLocation the value for tb_order_warehouse_location_transfer_ncm.new_location
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setNewLocation(String newLocation) {
        this.newLocation = newLocation == null ? null : newLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.remark
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.remark
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.remark
     *
     * @param remark the value for tb_order_warehouse_location_transfer_ncm.remark
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.create_time
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.create_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.create_time
     *
     * @param createTime the value for tb_order_warehouse_location_transfer_ncm.create_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.update_time
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.update_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.update_time
     *
     * @param updateTime the value for tb_order_warehouse_location_transfer_ncm.update_time
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.create_user
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.create_user
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.create_user
     *
     * @param createUser the value for tb_order_warehouse_location_transfer_ncm.create_user
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.update_user
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.update_user
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.update_user
     *
     * @param updateUser the value for tb_order_warehouse_location_transfer_ncm.update_user
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_warehouse_location_transfer_ncm.enable
     *
     * @return the value of tb_order_warehouse_location_transfer_ncm.enable
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_warehouse_location_transfer_ncm.enable
     *
     * @param enable the value for tb_order_warehouse_location_transfer_ncm.enable
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}