package com.yc.demo.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_status_flow_record
 *
 * @mbg.generated do_not_delete_during_merge Thu Aug 12 19:55:44 CST 2021
 */
public class TbStatusFlowRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.id
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   操作人code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.work_user_code
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private String workUserCode;

    /**
     * Database Column Remarks:
     *   操作人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.work_user_name
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private String workUserName;

    /**
     * Database Column Remarks:
     *   针对内容的自定义备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.content_remrk
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private String contentRemrk;

    /**
     * Database Column Remarks:
     *   操作人填写的内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.content
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.remark
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.create_time
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.update_time
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.create_user
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.update_user
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private Long updateUser;

    /**
     * Database Column Remarks:
     *   1可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.enable
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private Integer enable;

    /**
     * Database Column Remarks:
     *   权限code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.acl_code
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private String aclCode;

    /**
     * Database Column Remarks:
     *   对应哪种单据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.def_type
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private Integer defType;

    /**
     * Database Column Remarks:
     *   一个组有多个单子,但是签字的人是一个人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_status_flow_record.group_id
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    private String groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.id
     *
     * @return the value of tb_status_flow_record.id
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.id
     *
     * @param id the value for tb_status_flow_record.id
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.work_user_code
     *
     * @return the value of tb_status_flow_record.work_user_code
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public String getWorkUserCode() {
        return workUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.work_user_code
     *
     * @param workUserCode the value for tb_status_flow_record.work_user_code
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setWorkUserCode(String workUserCode) {
        this.workUserCode = workUserCode == null ? null : workUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.work_user_name
     *
     * @return the value of tb_status_flow_record.work_user_name
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public String getWorkUserName() {
        return workUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.work_user_name
     *
     * @param workUserName the value for tb_status_flow_record.work_user_name
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setWorkUserName(String workUserName) {
        this.workUserName = workUserName == null ? null : workUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.content_remrk
     *
     * @return the value of tb_status_flow_record.content_remrk
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public String getContentRemrk() {
        return contentRemrk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.content_remrk
     *
     * @param contentRemrk the value for tb_status_flow_record.content_remrk
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setContentRemrk(String contentRemrk) {
        this.contentRemrk = contentRemrk == null ? null : contentRemrk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.content
     *
     * @return the value of tb_status_flow_record.content
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.content
     *
     * @param content the value for tb_status_flow_record.content
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.remark
     *
     * @return the value of tb_status_flow_record.remark
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.remark
     *
     * @param remark the value for tb_status_flow_record.remark
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.create_time
     *
     * @return the value of tb_status_flow_record.create_time
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.create_time
     *
     * @param createTime the value for tb_status_flow_record.create_time
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.update_time
     *
     * @return the value of tb_status_flow_record.update_time
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.update_time
     *
     * @param updateTime the value for tb_status_flow_record.update_time
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.create_user
     *
     * @return the value of tb_status_flow_record.create_user
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.create_user
     *
     * @param createUser the value for tb_status_flow_record.create_user
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.update_user
     *
     * @return the value of tb_status_flow_record.update_user
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.update_user
     *
     * @param updateUser the value for tb_status_flow_record.update_user
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.enable
     *
     * @return the value of tb_status_flow_record.enable
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.enable
     *
     * @param enable the value for tb_status_flow_record.enable
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.acl_code
     *
     * @return the value of tb_status_flow_record.acl_code
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public String getAclCode() {
        return aclCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.acl_code
     *
     * @param aclCode the value for tb_status_flow_record.acl_code
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setAclCode(String aclCode) {
        this.aclCode = aclCode == null ? null : aclCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.def_type
     *
     * @return the value of tb_status_flow_record.def_type
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public Integer getDefType() {
        return defType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.def_type
     *
     * @param defType the value for tb_status_flow_record.def_type
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setDefType(Integer defType) {
        this.defType = defType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_status_flow_record.group_id
     *
     * @return the value of tb_status_flow_record.group_id
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_status_flow_record.group_id
     *
     * @param groupId the value for tb_status_flow_record.group_id
     *
     * @mbg.generated Thu Aug 12 19:55:44 CST 2021
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }
}