package com.yc.demo.domain;

import com.yc.demo.domain.ex.BasePoJo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_user
 *
 * @mbg.generated do_not_delete_during_merge Tue Mar 23 20:12:35 CST 2021
 */
public class TbUser extends BasePoJo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_name
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_code
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private Long userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.phone
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.remark
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.create_time
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.update_time
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   1可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.enable
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private Integer enable;

    /**
     * Database Column Remarks:
     *   登录人code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.login_code
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    private String loginCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param userName the value for tb_user.user_name
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_code
     *
     * @return the value of tb_user.user_code
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public Long getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_code
     *
     * @param userCode the value for tb_user.user_code
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setUserCode(Long userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone
     *
     * @return the value of tb_user.phone
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone
     *
     * @param phone the value for tb_user.phone
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.remark
     *
     * @return the value of tb_user.remark
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.remark
     *
     * @param remark the value for tb_user.remark
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.create_time
     *
     * @return the value of tb_user.create_time
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.create_time
     *
     * @param createTime the value for tb_user.create_time
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.update_time
     *
     * @return the value of tb_user.update_time
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.update_time
     *
     * @param updateTime the value for tb_user.update_time
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.enable
     *
     * @return the value of tb_user.enable
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.enable
     *
     * @param enable the value for tb_user.enable
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.login_code
     *
     * @return the value of tb_user.login_code
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public String getLoginCode() {
        return loginCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.login_code
     *
     * @param loginCode the value for tb_user.login_code
     *
     * @mbg.generated Tue Mar 23 20:12:35 CST 2021
     */
    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode == null ? null : loginCode.trim();
    }
}