server:
  port: 8886
info:
  api-doc: /swagger-ui.html
spring:
  application:
    name: ycdemo
  profiles:
    active: @spring.profiles.active@
---
spring.profiles: test
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
       url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
       username: root
       password: 123
       stat-view-servlet:
        enabled: false
       web-stat-filter:
        enabled: false
       filter:
        config:
          enabled: false
       validationQuery: select 'x'
       poolPreparedStatements: false
       removeAbandoned: true
       removeAbandonedTimeout: 180
       logAbandoned: false
       min-idle: 30
       maxWait: 60000
       max-active: 200
       test-on-borrow: false
       driver-class-name: com.mysql.jdbc.Driver
       test-on-return: false
       test-while-idle: true
       max-open-prepared-statements: 20
       max-pool-prepared-statement-per-connection-size: 50
       time-between-eviction-runs-millis: 60000
       min-evictable-idle-time-millis: 300000


mybatis:
  type-aliases-package: com.yc.demo.domain
  mapper-locations: classpath:mapper/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
logging:
  level.com.yc.demo.mapper: debug
  # 当前项目生成指定日志名的日志文件，文件名前添加完整路径，则在指定路径下生成日志
#  file:
  # 指定路径，则在该路径下生成默认名称为 spring.log 的日志文件
#  path:
  # 指定日志输出的等级 trace<debug<info<warn<error，默认级别为 info
---
spring.profiles: preview
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
       url: jdbc:mysql://39.101.65.222:3306/industry?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
       username: root
       password: 123456
       stat-view-servlet:
        enabled: false
       web-stat-filter:
        enabled: false
       filter:
        config:
          enabled: false
       validationQuery: select 'x'
       poolPreparedStatements: false
       removeAbandoned: true
       removeAbandonedTimeout: 180
       logAbandoned: false
       min-idle: 30
       maxWait: 60000
       max-active: 200
       test-on-borrow: false
       driver-class-name: com.mysql.jdbc.Driver
       test-on-return: false
       test-while-idle: true
       max-open-prepared-statements: 20
       max-pool-prepared-statement-per-connection-size: 50
       time-between-eviction-runs-millis: 60000
       min-evictable-idle-time-millis: 300000


mybatis:
  type-aliases-package: com.yc.demo.domain
  mapper-locations: classpath:mapper/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
logging:
  level.com.yc.demo.mapper: debug
  # 当前项目生成指定日志名的日志文件，文件名前添加完整路径，则在指定路径下生成日志
#  file:
  # 指定路径，则在该路径下生成默认名称为 spring.log 的日志文件
#  path:
  # 指定日志输出的等级 trace<debug<info<warn<error，默认级别为 info
---
spring.profiles: prod
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
       url: jdbc:mysql://39.101.65.222:3306/industry?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
       username: root
       password: 123456
       stat-view-servlet:
        enabled: false
       web-stat-filter:
        enabled: false
       filter:
        config:
          enabled: false
       validationQuery: select 'x'
       poolPreparedStatements: false
       removeAbandoned: true
       removeAbandonedTimeout: 180
       logAbandoned: false
       min-idle: 30
       maxWait: 60000
       max-active: 200
       test-on-borrow: false
       driver-class-name: com.mysql.jdbc.Driver
       test-on-return: false
       test-while-idle: true
       max-open-prepared-statements: 20
       max-pool-prepared-statement-per-connection-size: 50
       time-between-eviction-runs-millis: 60000
       min-evictable-idle-time-millis: 300000

mybatis:
  type-aliases-package: com.yc.demo.domain
  mapper-locations: classpath:mapper/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
logging:
  level.com.yc.demo.mapper: debug
  # 当前项目生成指定日志名的日志文件，文件名前添加完整路径，则在指定路径下生成日志
#  file:
  # 指定路径，则在该路径下生成默认名称为 spring.log 的日志文件
#  path:
  # 指定日志输出的等级 trace<debug<info<warn<error，默认级别为 info
