package com.yc.demo.mapper;

import com.yc.demo.domain.TbAcl;
import com.yc.demo.domain.TbAclExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    long countByExample(TbAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    int deleteByExample(TbAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    int insert(TbAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    int insertSelective(TbAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    List<TbAcl> selectByExample(TbAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    TbAcl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbAcl record, @Param("example") TbAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    int updateByExample(@Param("record") TbAcl record, @Param("example") TbAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    int updateByPrimaryKeySelective(TbAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acl
     *
     * @mbg.generated Sat May 29 19:24:33 CST 2021
     */
    int updateByPrimaryKey(TbAcl record);
}