package com.yc.demo.mapper;

import com.yc.demo.domain.TbCheckInfoDetail;
import com.yc.demo.domain.TbCheckInfoDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCheckInfoDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    long countByExample(TbCheckInfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    int deleteByExample(TbCheckInfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    int insert(TbCheckInfoDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    int insertSelective(TbCheckInfoDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    List<TbCheckInfoDetail> selectByExample(TbCheckInfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    TbCheckInfoDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbCheckInfoDetail record, @Param("example") TbCheckInfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    int updateByExample(@Param("record") TbCheckInfoDetail record, @Param("example") TbCheckInfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    int updateByPrimaryKeySelective(TbCheckInfoDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check_info_detail
     *
     * @mbg.generated Mon Mar 01 14:32:21 CST 2021
     */
    int updateByPrimaryKey(TbCheckInfoDetail record);

    void batchInsert(List<TbCheckInfoDetail> list);

    void batchUpdate(List<TbCheckInfoDetail> list);
}