package com.yc.demo.mapper;

import com.yc.demo.domain.TbDefinitionStateFlow;
import com.yc.demo.domain.TbDefinitionStateFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDefinitionStateFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    long countByExample(TbDefinitionStateFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    int deleteByExample(TbDefinitionStateFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    int insert(TbDefinitionStateFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    int insertSelective(TbDefinitionStateFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    List<TbDefinitionStateFlow> selectByExample(TbDefinitionStateFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    TbDefinitionStateFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbDefinitionStateFlow record, @Param("example") TbDefinitionStateFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    int updateByExample(@Param("record") TbDefinitionStateFlow record, @Param("example") TbDefinitionStateFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    int updateByPrimaryKeySelective(TbDefinitionStateFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_definition_state_flow
     *
     * @mbg.generated Fri Jun 04 15:47:02 CST 2021
     */
    int updateByPrimaryKey(TbDefinitionStateFlow record);
}