package com.yc.demo.mapper;

import com.yc.demo.domain.TbMapRelation;
import com.yc.demo.domain.TbMapRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbMapRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    long countByExample(TbMapRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    int deleteByExample(TbMapRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    int insert(TbMapRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    int insertSelective(TbMapRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    List<TbMapRelation> selectByExample(TbMapRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    TbMapRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbMapRelation record, @Param("example") TbMapRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    int updateByExample(@Param("record") TbMapRelation record, @Param("example") TbMapRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    int updateByPrimaryKeySelective(TbMapRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_map_relation
     *
     * @mbg.generated Sat Apr 03 23:06:19 CST 2021
     */
    int updateByPrimaryKey(TbMapRelation record);

    void batchInsert(List<TbMapRelation> list);
}