package com.yc.demo.mapper;

import com.yc.demo.domain.TbOrderWarehouseLocationTransfer;
import com.yc.demo.domain.TbOrderWarehouseLocationTransferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbOrderWarehouseLocationTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    long countByExample(TbOrderWarehouseLocationTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    int deleteByExample(TbOrderWarehouseLocationTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    int insert(TbOrderWarehouseLocationTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    int insertSelective(TbOrderWarehouseLocationTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    List<TbOrderWarehouseLocationTransfer> selectByExample(TbOrderWarehouseLocationTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    TbOrderWarehouseLocationTransfer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbOrderWarehouseLocationTransfer record, @Param("example") TbOrderWarehouseLocationTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    int updateByExample(@Param("record") TbOrderWarehouseLocationTransfer record, @Param("example") TbOrderWarehouseLocationTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    int updateByPrimaryKeySelective(TbOrderWarehouseLocationTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer
     *
     * @mbg.generated Sat May 29 19:26:28 CST 2021
     */
    int updateByPrimaryKey(TbOrderWarehouseLocationTransfer record);
}