package com.yc.demo.mapper;

import com.yc.demo.domain.TbOrderWarehouseLocationTransferNcm;
import com.yc.demo.domain.TbOrderWarehouseLocationTransferNcmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbOrderWarehouseLocationTransferNcmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    long countByExample(TbOrderWarehouseLocationTransferNcmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    int deleteByExample(TbOrderWarehouseLocationTransferNcmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    int insert(TbOrderWarehouseLocationTransferNcm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    int insertSelective(TbOrderWarehouseLocationTransferNcm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    List<TbOrderWarehouseLocationTransferNcm> selectByExample(TbOrderWarehouseLocationTransferNcmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    TbOrderWarehouseLocationTransferNcm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbOrderWarehouseLocationTransferNcm record, @Param("example") TbOrderWarehouseLocationTransferNcmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    int updateByExample(@Param("record") TbOrderWarehouseLocationTransferNcm record, @Param("example") TbOrderWarehouseLocationTransferNcmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    int updateByPrimaryKeySelective(TbOrderWarehouseLocationTransferNcm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_warehouse_location_transfer_ncm
     *
     * @mbg.generated Thu Aug 12 19:12:56 CST 2021
     */
    int updateByPrimaryKey(TbOrderWarehouseLocationTransferNcm record);
    void batchInsert(List<TbOrderWarehouseLocationTransferNcm> list);

    void batchUpdate(List<TbOrderWarehouseLocationTransferNcm> list);
}