package com.yc.demo.mapper;

import com.yc.demo.domain.TbTestItems;
import com.yc.demo.domain.TbTestItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTestItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    long countByExample(TbTestItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    int deleteByExample(TbTestItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    int insert(TbTestItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    int insertSelective(TbTestItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    List<TbTestItems> selectByExample(TbTestItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    TbTestItems selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbTestItems record, @Param("example") TbTestItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    int updateByExample(@Param("record") TbTestItems record, @Param("example") TbTestItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    int updateByPrimaryKeySelective(TbTestItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_items
     *
     * @mbg.generated Sun Apr 04 02:25:16 CST 2021
     */
    int updateByPrimaryKey(TbTestItems record);
}