package com.yc.demo.mapper;

import com.yc.demo.domain.TbUserRoleRelation;
import com.yc.demo.domain.TbUserRoleRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    long countByExample(TbUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    int deleteByExample(TbUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    int insert(TbUserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    int insertSelective(TbUserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    List<TbUserRoleRelation> selectByExample(TbUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    TbUserRoleRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") TbUserRoleRelation record, @Param("example") TbUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    int updateByExample(@Param("record") TbUserRoleRelation record, @Param("example") TbUserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    int updateByPrimaryKeySelective(TbUserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role_relation
     *
     * @mbg.generated Sat May 29 19:24:21 CST 2021
     */
    int updateByPrimaryKey(TbUserRoleRelation record);

    void batchInsert(List<TbUserRoleRelation> list);
}